app/jokes/routes.py
from flask import Blueprint, flash, request, redirect, url_for, render_template, abort
from flask_login import current_user, login_required
import requests
from app import db
from app.jokes.models import Joke
from app.jokes.forms import JokeForm

jokes = Blueprint('jokes', __name__)


# Добавить шутку
@jokes.route('/joke/create', methods=['GET', 'POST'])
@login_required
def create():

    form_joke = JokeForm()
    user_id = current_user.id
    if form_joke.validate_on_submit():
        joke_add = Joke(title=form_joke.title.data,
                        description=form_joke.description.data,
                        user_id=user_id)

        # Добавляем в базу данных
        try:
            db.session.add(joke_add)
            db.session.commit()
            flash("Ваша шутка добавлена!")
            return redirect(url_for('main.index'))
        except IndexError:
            flash("Возникла проблема при создании шутки")
    return render_template('jokes/create.html', title='Добавить шутку', \
                           form=form_joke, legend='Добавить шутку')


# Генерация шутки с внешнего сервиса
@jokes.route('/joke/generation')
@login_required
def generation():
    res = requests.get('https://geek-jokes.sameerkumar.website/api')
    print(res.text)
    user_id = current_user.id
    joke_gen = Joke(title='Сгенерированая шутка',
                    description=res.text,
                    user_id=user_id)
    # Добавляем в базу данных
    try:
        db.session.add(joke_gen)
        db.session.commit()
        flash("Ваша шутка добавлена!")
        return redirect(url_for('main.index'))
    except IndexError:
        flash("Возникла проблема при создании шутки", "Внимание!")


# Обновить шутку
@jokes.route('/joke/<int:joke_id>/update', methods=['GET', 'POST'])
@login_required
def update(joke_id):
    joke_upd = db.session.query(Joke).filter(Joke.id == joke_id).first()
    joke_list = db.session.query(Joke).filter_by(user_id=current_user.id).all()
    joke_list_all = db.session.query(Joke).all()

    # Проверка существования
    if joke_upd in joke_list_all:
        pass
    else:
        return abort(404)

    # Проверка доступа
    if joke_upd in joke_list:
        pass
    else:
        return abort(403)

    if request.method == 'POST':
        form_joke = JokeForm(formdata=request.form, obj=joke_id)
        form_joke.populate_obj(joke_upd)

        db.session.commit()
        flash("Ваша шутка отредактирована!", "Успешно")
        return redirect(url_for('main.index', joke_id=joke_upd.id))

    form_joke = JokeForm(obj=joke_upd)
    return render_template('jokes/update.html', title='Редактирование шутки',
                           form=form_joke, joke=joke_upd, legend='Шутка отредактирована')


# Удалить шутку
@jokes.route('/joke/<int:joke_id>/delete', methods=['POST'])
@login_required
def delete(joke_id):
    joke_del = db.session.query(Joke).get_or_404(joke_id)

    try:
        db.session.delete(joke_del)
        db.session.commit()
        flash("Ваша шутка удалена!")
        return redirect(url_for('main.index'))
    except IndexError:
        flash("Возникла непредвиденная ошибка при удалении!")


# Получить шутку по ID
@jokes.route('/joke/<joke_id>', methods=['GET'])
@login_required
def joke(joke_id):
    joke_view = db.session.query(Joke).filter(Joke.id == joke_id).first()
    joke_list = db.session.query(Joke).filter_by(user_id=current_user.id).all()
    joke_list_all = db.session.query(Joke).all()

    # Проверка существования
    if joke_view in joke_list_all:
        pass
    else:
        return abort(404)

    # Проверка доступа
    if joke_view in joke_list:
        pass
    else:
        return abort(403)

    form_joke = JokeForm(obj=joke_view)
    return render_template('jokes/views.html', title='Просмотр шутки',
                           form=form_joke, joke=joke_view, legend='Просмотр шутки')

app/main/routes.py
from flask import Blueprint, redirect, url_for, render_template, request, abort
from flask_login import current_user, login_required

from app import db
from app.jokes.models import Joke

main = Blueprint('main', __name__)


# Маршрут домашней страницы
@main.route('/', methods=['GET'])
def home():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    else:
        return render_template('main/home.html')


# Маршрут домашней страницы
@main.route('/index', methods=['GET'])
@login_required
def index():
    user_id = current_user.id
    jokes = db.session.query(Joke).filter(Joke.user_id == user_id).all()
    return render_template('main/index.html', jokes=jokes)

app/users/routes.py
from flask import Blueprint, flash, redirect, url_for, request, render_template
from flask_login import current_user, login_user, logout_user
from werkzeug.security import generate_password_hash
from werkzeug.urls import url_parse

from app import db
from app.users.models import User
from app.users.forms import LoginForm, RegistrationForm

users = Blueprint('users', __name__)


# Маршрут входа пользователя
@users.route('/login', methods=['GET', 'POST'])
def login():
    login_form = LoginForm()

    # Разрешаем вход в систему если проверка прошла успешно
    if login_form.validate_on_submit():
        user = db.session.query(User) \
                .filter_by(username=login_form.username.data).first()
        if user is None or not user \
                .check_password(login_form.password.data):
            flash("Неверное имя пользователя или пароль")
            return redirect(url_for('users.login'))
        login_user(user, remember=login_form.remember_me.data)
        next_page = request.args.get('next')
        if not next_page or url_parse(next_page).netloc != '':
            next_page = url_for('main.index')
        return redirect(next_page)
    return render_template('auth/login.html', form=login_form)


# Выход пользователя
@users.route('/logout', methods=['GET'])
def logout():
    user = current_user
    user.authenticated = False
    db.session.add(user)
    db.session.commit()
    logout_user()
    flash("Вы вышли из системы")
    return redirect(url_for('main.home'))


# Маршрут регистрации пользователя
@users.route('/registration', methods=['GET', 'POST'])
def registration():
    reg_form = RegistrationForm()

    # Обновляем БД в случае успешной проверки
    if reg_form.validate_on_submit():
        username = reg_form.username.data
        password = reg_form.password.data

        # Hash пароля
        password_hash = generate_password_hash(password)

        # Добавим username и hashed passowd в БД
        new_user = User(username=username,
                        password_hash=password_hash)
        db.session.add(new_user)
        db.session.commit()

        flash("Спасибо! Теперь вы являетесь зарегистрированным пользователем")
        return redirect(url_for('users.login'))
    return render_template('auth/registration.html', form=reg_form)

app/templates/main/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <title>JokesManager</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="#">

</head>
<body>
<header class="site-header">
        <div>
            JokesManager:
            {% if current_user.is_authenticated %}
                <a href="/index">Главная</a>
                <a href="{{ url_for('users.logout') }}"
                   class="btn">Выйти</a>
            {% else %}
                <a href="{{ url_for('users.login') }}"
                   class="btn">Войти</a>
            {% endif %}
        </div>
        <div class="login-panel">
            {% if current_user.is_authenticated %}
                <a href="{{ url_for('jokes.create') }}"
                   class="btn">Создать шутку</a>
                <a href="{{ url_for('jokes.generation') }}"
                   class="btn">Сгенерировать шутку</a>
            {% else %}
            {% endif %}
        </div>
</header>
<main role="main" class="container-xl">
    <div class="row">
        <div class="col-md-12">
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    <div class="flashes">
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }}">{{ message }}</div>
                        {% endfor %}
                    </div>
                {% endif %}
            {% endwith %}
            {% block content %}{% endblock %}
        </div>
    </div>
</main>
</body>
</html>

app/templates/main/home.html
{% extends "main/base.html" %}
{% block content %}
    <h1>Пожалуйста войдите в систему!</h1>
{% endblock content %}

app/templates/main/index.html
{% extends "main/base.html" %}
{% block content %}
    <div class="col-md-12">
        <table class="table table-striped">
            <tr>
                <th scope="col">Имя</th>
                <th scope="col">Текст шутки</th>
                <th scope="col">Время добавления</th>
                <th scope="col">Время последнего обновления</th>
                <th scope="col">Действия</th>
            </tr>
            {% for joke in jokes %}
                <tr class="data-hover">
                    <td>{{ joke.title }}</td>
                    <td>{{ joke.description }}</td>
                    <td>{{ joke.created_by.strftime('%Y-%m-%d %H:%M:%S') }}</td>
                    <td>
                        {% if joke.updated_at %}
                            {{ joke.updated_at.strftime('%Y-%m-%d %H:%M:%S') }}
                        {% else %}{% endif %}
                    </td>
                    <td>
                        <a href="{{ url_for('jokes.update', joke_id=joke.id) }}" class="btn">Редактировать</a>
                        <form action="{{ url_for('jokes.delete', joke_id=joke.id) }}" method="POST">
                            <input class="btn" type="submit" value="Удалить">
                        </form>
                    </td>
                </tr>
            {% else %}
            {% endfor %}
        </table>
    </div>
{% endblock content %}